! CE2 FRR Configuration
! Role: Customer Edge for VRF 10 (PE2 side)
! eBGP ASN 65001, peers with PE2 (ASN 65000)
frr version 8.5
frr defaults traditional
hostname ce2
log syslog informational
!
router bgp 65001
 bgp router-id 100.64.5.20
 no bgp ebgp-requires-policy
 !
 neighbor 100.64.5.10 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 100.64.5.10 activate
  network 100.64.5.0/24
  network 10.1.2.0/24
  redistribute connected
 exit-address-family
!
end
